<?php
global $pasdoc;
$pasdoc = array(
  'ok_operator_test' => array('html_filename' => 'ok_operator_test.html', 'type' => 'unit'),
  ':=' => array('html_filename' => 'ok_operator_test.html#:=', 'type' => 'operator'),
  '+' => array('html_filename' => 'ok_operator_test.html#+', 'type' => 'operator'),
  '-' => array('html_filename' => 'ok_operator_test.html#-', 'type' => 'operator'),
  '*' => array('html_filename' => 'ok_operator_test.html#*', 'type' => 'operator'),
  '/' => array('html_filename' => 'ok_operator_test.html#/', 'type' => 'operator'),
  '**' => array('html_filename' => 'ok_operator_test.html#**', 'type' => 'operator'),
  '=' => array('html_filename' => 'ok_operator_test.html#=', 'type' => 'operator'),
  '<' => array('html_filename' => 'ok_operator_test.html#<', 'type' => 'operator'),
  '>' => array('html_filename' => 'ok_operator_test.html#>', 'type' => 'operator'),
  '<=' => array('html_filename' => 'ok_operator_test.html#<=', 'type' => 'operator'),
  '>=' => array('html_filename' => 'ok_operator_test.html#>=', 'type' => 'operator'),
  'or' => array('html_filename' => 'ok_operator_test.html#or', 'type' => 'operator'),
  'and' => array('html_filename' => 'ok_operator_test.html#and', 'type' => 'operator'),
  'xor' => array('html_filename' => 'ok_operator_test.html#xor', 'type' => 'operator'),
  'TDelphiRec' => array('html_filename' => 'ok_operator_test.TDelphiRec.html', 'type' => 'record'),
  'TDelphiRec.Add' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Add', 'type' => 'operator'),
  'TDelphiRec.Subtract' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Subtract', 'type' => 'operator'),
  'TDelphiRec.Implicit' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Implicit', 'type' => 'operator'),
  'TDelphiRec.Implicit' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Implicit', 'type' => 'operator'),
  'TDelphiRec.Explicit' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Explicit', 'type' => 'operator'),
  'TMyClass' => array('html_filename' => 'ok_operator_test.TMyClass.html', 'type' => 'class'),
  'TMyClass.Operator' => array('html_filename' => 'ok_operator_test.TMyClass.html#Operator', 'type' => 'property'),
  'TMyType' => array('html_filename' => 'ok_operator_test.TMyType.html', 'type' => 'record'),
  'TMyType2' => array('html_filename' => 'ok_operator_test.TMyType2.html', 'type' => 'record'),
);
