<?php
global $pasdoc;
$pasdoc = array(
  'ok_operator_test' => array('html_filename' => 'ok_operator_test.html', 'type' => 'unit'),
  ':=' => array('html_filename' => 'ok_operator_test.html#:=-TMyType2-', 'type' => 'operator'),
  '+' => array('html_filename' => 'ok_operator_test.html#+-TMyType-TMyType-', 'type' => 'operator'),
  '-' => array('html_filename' => 'ok_operator_test.html#--TMyType-TMyType-', 'type' => 'operator'),
  '*' => array('html_filename' => 'ok_operator_test.html#*-TMyType-integer-', 'type' => 'operator'),
  '/' => array('html_filename' => 'ok_operator_test.html#/-TMyType-TMyType-', 'type' => 'operator'),
  '**' => array('html_filename' => 'ok_operator_test.html#**-TMyType-TMyType-', 'type' => 'operator'),
  '=' => array('html_filename' => 'ok_operator_test.html#=-TMyType-TMyType-', 'type' => 'operator'),
  '<' => array('html_filename' => 'ok_operator_test.html#<-TMyType-TMyType-', 'type' => 'operator'),
  '>' => array('html_filename' => 'ok_operator_test.html#>-TMyType-TMyType-', 'type' => 'operator'),
  '<=' => array('html_filename' => 'ok_operator_test.html#<=-TMyType-TMyType-', 'type' => 'operator'),
  '>=' => array('html_filename' => 'ok_operator_test.html#>=-TMyType-TMyType-', 'type' => 'operator'),
  'or' => array('html_filename' => 'ok_operator_test.html#or-TMyType-TMyType-', 'type' => 'operator'),
  'and' => array('html_filename' => 'ok_operator_test.html#and-TMyType-TMyType-', 'type' => 'operator'),
  'xor' => array('html_filename' => 'ok_operator_test.html#xor-TMyType-TMyType-', 'type' => 'operator'),
  'TDelphiRec' => array('html_filename' => 'ok_operator_test.TDelphiRec.html', 'type' => 'record'),
  'TDelphiRec.Add' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Add-TDelphiRec-TDelphiRec-', 'type' => 'operator'),
  'TDelphiRec.Subtract' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Subtract-TDelphiRec-TDelphiRec-', 'type' => 'operator'),
  'TDelphiRec.Implicit' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Implicit-Integer-', 'type' => 'operator'),
  'TDelphiRec.Implicit' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Implicit-TDelphiRec-', 'type' => 'operator'),
  'TDelphiRec.Explicit' => array('html_filename' => 'ok_operator_test.TDelphiRec.html#Explicit-Double-', 'type' => 'operator'),
  'TMyClass' => array('html_filename' => 'ok_operator_test.TMyClass.html', 'type' => 'class'),
  'TMyClass.Operator' => array('html_filename' => 'ok_operator_test.TMyClass.html#Operator', 'type' => 'property'),
  'TMyType' => array('html_filename' => 'ok_operator_test.TMyType.html', 'type' => 'record'),
  'TMyType2' => array('html_filename' => 'ok_operator_test.TMyType2.html', 'type' => 'record'),
);
