<?php
global $pasdoc;
$pasdoc = array(
  'ok_inherited_members' => array('html_filename' => 'ok_inherited_members.html', 'type' => 'unit'),
  'TBase' => array('html_filename' => 'ok_inherited_members.TBase.html', 'type' => 'class'),
  'TBase.BaseMethod' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseMethod', 'type' => 'procedure'),
  'TBase.BaseMethod2' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseMethod2', 'type' => 'procedure'),
  'TBase.BaseProtectedMethod' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseProtectedMethod', 'type' => 'procedure'),
  'TBase.BaseConst' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseConst', 'type' => 'constant'),
  'TBase.BaseConst2' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseConst2', 'type' => 'constant'),
  'TBase.A' => array('html_filename' => 'ok_inherited_members.TBase.html#A', 'type' => 'variable'),
  'TBase.B' => array('html_filename' => 'ok_inherited_members.TBase.html#B', 'type' => 'variable'),
  'TBase.BaseField' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseField', 'type' => 'variable'),
  'TBase.BaseField2' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseField2', 'type' => 'variable'),
  'TBase.BaseField3' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseField3', 'type' => 'variable'),
  'TBase.BaseProtectedField' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseProtectedField', 'type' => 'variable'),
  'TBase.Y' => array('html_filename' => 'ok_inherited_members.TBase.html#Y', 'type' => 'variable'),
  'TBase.Z' => array('html_filename' => 'ok_inherited_members.TBase.html#Z', 'type' => 'variable'),
  'TBase.BaseProp' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseProp', 'type' => 'property'),
  'TBase.BaseProp2' => array('html_filename' => 'ok_inherited_members.TBase.html#BaseProp2', 'type' => 'property'),
  'TBase.TBaseEnum' => array('html_filename' => 'ok_inherited_members.TBase.html#TBaseEnum', 'type' => 'type'),
  'TBase.meOne' => array('html_filename' => 'ok_inherited_members.TBase.html#meOne', 'type' => 'enum constant'),
  'TBase.meTwo' => array('html_filename' => 'ok_inherited_members.TBase.html#meTwo', 'type' => 'enum constant'),
  'TBase.TBaseType' => array('html_filename' => 'ok_inherited_members.TBase.html#TBaseType', 'type' => 'type'),
  'TBase.TBaseNestedCio' => array('html_filename' => 'ok_inherited_members.TBase.TBaseNestedCio.html', 'type' => 'class'),
  'TBase.TBaseNestedCio.NestedMethod' => array('html_filename' => 'ok_inherited_members.TBase.TBaseNestedCio.html#NestedMethod', 'type' => 'procedure'),
  'TDerived' => array('html_filename' => 'ok_inherited_members.TDerived.html', 'type' => 'class'),
  'TDerived.DerivedMethod' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedMethod', 'type' => 'procedure'),
  'TDerived.DerivedMethod2' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedMethod2', 'type' => 'procedure'),
  'TDerived.DerivedProtectedMethod' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedProtectedMethod', 'type' => 'procedure'),
  'TDerived.DerivedConst' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedConst', 'type' => 'constant'),
  'TDerived.DerivedConst2' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedConst2', 'type' => 'constant'),
  'TDerived.A2' => array('html_filename' => 'ok_inherited_members.TDerived.html#A2', 'type' => 'variable'),
  'TDerived.B2' => array('html_filename' => 'ok_inherited_members.TDerived.html#B2', 'type' => 'variable'),
  'TDerived.DerivedField' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedField', 'type' => 'variable'),
  'TDerived.DerivedField2' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedField2', 'type' => 'variable'),
  'TDerived.DerivedField3' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedField3', 'type' => 'variable'),
  'TDerived.DerivedProtectedField' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedProtectedField', 'type' => 'variable'),
  'TDerived.Y2' => array('html_filename' => 'ok_inherited_members.TDerived.html#Y2', 'type' => 'variable'),
  'TDerived.Z2' => array('html_filename' => 'ok_inherited_members.TDerived.html#Z2', 'type' => 'variable'),
  'TDerived.DerivedProp' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedProp', 'type' => 'property'),
  'TDerived.DerivedProp2' => array('html_filename' => 'ok_inherited_members.TDerived.html#DerivedProp2', 'type' => 'property'),
  'TDerived.TDerivedEnum' => array('html_filename' => 'ok_inherited_members.TDerived.html#TDerivedEnum', 'type' => 'type'),
  'TDerived.meOne' => array('html_filename' => 'ok_inherited_members.TDerived.html#meOne', 'type' => 'enum constant'),
  'TDerived.meTwo' => array('html_filename' => 'ok_inherited_members.TDerived.html#meTwo', 'type' => 'enum constant'),
  'TDerived.TDerivedType' => array('html_filename' => 'ok_inherited_members.TDerived.html#TDerivedType', 'type' => 'type'),
  'TDerived.TDerivedNestedCio' => array('html_filename' => 'ok_inherited_members.TDerived.TDerivedNestedCio.html', 'type' => 'class'),
  'TDerived.TDerivedNestedCio.NestedMethod' => array('html_filename' => 'ok_inherited_members.TDerived.TDerivedNestedCio.html#NestedMethod', 'type' => 'procedure'),
  'TNewDerived' => array('html_filename' => 'ok_inherited_members.TNewDerived.html', 'type' => 'class'),
  'TNewDerived.NewDerivedMethod' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedMethod', 'type' => 'procedure'),
  'TNewDerived.NewDerivedMethod2' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedMethod2', 'type' => 'procedure'),
  'TNewDerived.NewDerivedProtectedMethod' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedProtectedMethod', 'type' => 'procedure'),
  'TNewDerived.NewDerivedConst' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedConst', 'type' => 'constant'),
  'TNewDerived.NewDerivedConst2' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedConst2', 'type' => 'constant'),
  'TNewDerived.A3' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#A3', 'type' => 'variable'),
  'TNewDerived.B3' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#B3', 'type' => 'variable'),
  'TNewDerived.NewDerivedField' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedField', 'type' => 'variable'),
  'TNewDerived.NewDerivedField2' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedField2', 'type' => 'variable'),
  'TNewDerived.NewDerivedField3' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedField3', 'type' => 'variable'),
  'TNewDerived.NewDerivedProtectedField' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedProtectedField', 'type' => 'variable'),
  'TNewDerived.Y3' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#Y3', 'type' => 'variable'),
  'TNewDerived.Z3' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#Z3', 'type' => 'variable'),
  'TNewDerived.NewDerivedProp' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedProp', 'type' => 'property'),
  'TNewDerived.NewDerivedProp2' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#NewDerivedProp2', 'type' => 'property'),
  'TNewDerived.TNewDerivedEnum' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#TNewDerivedEnum', 'type' => 'type'),
  'TNewDerived.meOne' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#meOne', 'type' => 'enum constant'),
  'TNewDerived.meTwo' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#meTwo', 'type' => 'enum constant'),
  'TNewDerived.TNewDerivedType' => array('html_filename' => 'ok_inherited_members.TNewDerived.html#TNewDerivedType', 'type' => 'type'),
  'TNewDerived.TNewDerivedNestedCio' => array('html_filename' => 'ok_inherited_members.TNewDerived.TNewDerivedNestedCio.html', 'type' => 'class'),
  'TNewDerived.TNewDerivedNestedCio.NestedMethod' => array('html_filename' => 'ok_inherited_members.TNewDerived.TNewDerivedNestedCio.html#NestedMethod', 'type' => 'procedure'),
);
