RTransTable = (
    {trNoTrans} '<what?>', //no ID assigned, so far
    {trLanguage} 'French',
  //map
    {trUnits} '<<<Unités>>>',
    {trClassHierarchy} 'Hiérarchie des classes',
    {trCio} 'Classes, interfaces, enregistrements et objets',
    {trInternalCR} strToDo, // 'Internal Classes and Records',
    {trInternalTypes} strToDo, // 'Internal Types',
    {trIdentifiers} 'Identificateurs',
    {trGvUses} 'Graphe de dépendance d''unités',
    {trGvClasses} 'Graphe de hiérarchie des classes',
  //tables and members
    {trClasses} strKeep, //'Classes',
      {trClass} 'Classe',
      {trDispInterface} strToDo, //'DispInterface',
      {trInterface} strKeep, //'Interface',
    {trObjects} 'Objets',
      {trObject} 'Objet',
      {trRecord} 'Enregistrement', //'Record',
        {trHierarchy} 'Hiérarchie',
        {trFields} 'Champs',
        {trMethods} 'Méthodes',
        {trProperties} 'Propriétés',
    {trLibrary} 'Bibliothèque', //?
    {trPackage} 'Paquet',  //'Package',
    {trProgram} 'Logiciel', //? 'Program',
    {trUnit} 'Unité',
      {trUses} strToDo, //'Uses',
      {trConstants} 'Constantes',
      {trFunctionsAndProcedures} 'Fonctions et procédures',
      {trTypes} strKeep, //'Types',
        {trType} strKeep, //'Type',
      {trVariables} strKeep, //'Variables',
      {trAuthors} 'Auteurs',
        {trAuthor} 'Auteur',
      {trCreated} 'Crée',
      {trLastModified} 'Dernière modification',
    {trSubroutine} strToDo, //'Subroutine',
      {trParameters} 'Paramètres',
      {trReturns} 'Retourne',
      {trExceptionsRaised} 'Exception levées', //'Exceptions raised',
    {trExceptions} strKeep, //'Exceptions',
      {trException} strKeep, //'Exception',
    {trEnum} 'Énumération', //'Enumeration',
  //visibilities
    {trVisibility} 'Visibilité',
      {trPrivate} 'Privé',
      {trStrictPrivate} 'Strictement Privé', //?
      {trProtected} 'Protégé',
      {trStrictProtected} 'Strictement Protégé', //?
      {trPublic} strKeep, //'Public',
      {trPublished} 'Publiés',
      {trAutomated} 'Automatisé',
      {trImplicit} strKeep, //'Implicit',
  //hints
    {trDeprecated} 'ce symbole est désapprouvé',
    {trPlatformSpecific} 'ce symbole est spécifique à une plateforme d''exécution',
    {trLibrarySpecific} 'ce symbole est spécifique à une certaine bibliothèque',
  //headings
    {trOverview} 'Aperçu',
    {trIntroduction} strKeep, //'Introduction',
    {trConclusion} strKeep, //'Conclusion',
    {trEnclosingClass} strToDo, //'Enclosing Class',
    {trHeadlineCio} 'Toutes les classes, interfaces, objets et enregistrements',
    {trHeadlineConstants} 'Toutes les constants',
    {trHeadlineFunctionsAndProcedures} 'Toutes les fonctions et procédures',
    {trHeadlineIdentifiers} 'Tous les identificateurs',
    {trHeadlineTypes} 'Tous les types',
    {trHeadlineUnits} 'Toutes les unités',
    {trHeadlineVariables} 'Toutes les variables',
    {trSummaryCio} 'Classes, interfaces, objets et enregistrements',
  //column headings
    {trDeclaration} 'Déclaration',
    {trDescription} strKeep, //'Description',
    {trDescriptions} strKeep, //'Descriptions', 'Detailed Descriptions'?
    {trName} 'Nom',
    {trValues} 'Valeurs', //?
  //empty
    {trNone} 'Aucun(e)(s)', //'Rien'?
    {trNoCIOs} 'L''unité ne contient ni classe, ni interface, ni objets, ni enregistrement.', 
    {trNoCIOsForHierarchy} 'L''unité ne contient ni classe, ni interface, ni objets.', 
    {trNoTypes} 'L''unité ne contient aucun type.', 
    {trNoVariables} 'L''unité ne contient aucune variable.', 
    {trNoConstants} 'L''unité ne contient aucune constante.', 
    {trNoFunctions} 'L''unité ne contient ni fonction ni procédure.', 
    {trNoIdentifiers} 'L''unité ne contient aucun indentificateur.', 
  //misc
    {trHelp} 'Aide',
    {trLegend} 'Légende',
    {trMarker} 'Marquage',
    {trWarningOverwrite} 'Attention, ne pas éditer - ce fichier est créé automatiquement et va être écrasé',
    {trWarning} 'Attention',
    {trGeneratedBy} 'Produit par',
    {trGeneratedOn} strToDo, //'Generated on'
    {trOnDateTime} 'le',
    {trSearch} 'Cherche', //? 'Recherche'
    {trSeeAlso} 'Voir aussi', //?
    {trInternal} strToDo, //'internal',
    {trAttributes} strToDo, //'Attributes',
    ''  //dummy
  );

