RTransTable = (
    {trNoTrans} '<what?>', //no ID assigned, so far
    {trLanguage} 'Spanish',
  //map
    {trUnits} 'Unidades',
    {trClassHierarchy} 'Jerarquía de clases',
    {trCio} 'Clases, interfaces y objetos',
    {trNestedCR} strToDo, // 'Nested Classes and Records',
    {trNestedTypes} strToDo, // 'Nested Types',
    {trIdentifiers} 'Identificadores',
    {trGvUses} 'Gráfico de dependencias de unidades', //
    {trGvClasses} 'Gráfico de jerarquía de clases', //
  //tables and members
    {trClasses} 'Clases',
      {trClass} 'Clase',
      {trDispInterface} strToDo, //'DispInterface',
      {trInterface} 'Interfaz', //'Interface',
    {trObjects} 'Objetos',
      {trObject} 'Objeto',
      {trRecord} 'Registro', //'Record',
      {trPacked} strToDo, //'Packed',
        {trHierarchy} 'Jerarquía',
        {trFields} 'Campos',
        {trMethods} 'Métodos',
        {trProperties} 'Propiedades',
    {trLibrary} 'Biblioteca',  //'Library',
    {trPackage} 'Paquete',  //'Package',
    {trProgram} 'Programa',  //'Program',
    {trUnit} 'Unidad',
      {trUses} 'Unidades', //'Uses', I may use "Unidades utilizadas/referenciadas" (Used/referenced units).
      {trConstants} 'Constantes',
      {trFunctionsAndProcedures} 'Funciones y procedimientos',
      {trTypes} 'Tipos',
        {trType} 'Tipo',
      {trVariables} 'Variables', //'Variables',
      {trAuthors} 'Autores',
        {trAuthor} 'Autor',
      {trCreated} 'Creado',
      {trLastModified} 'Última modificación',
    {trSubroutine} 'Subrutina', //'Subroutine',
      {trParameters} 'Parámetros',
      {trReturns} 'Retorno', //strToDo??? solo uno!
      {trExceptionsRaised} 'Excepciones lanzadas',
    {trExceptions} 'Excepciones',
      {trException} 'Excepción', //
    {trEnum} 'Enumeración', //'Enumeration',
  //visibilities
    {trVisibility} 'Visibilidad',
      {trPrivate} 'Privado', //'Private',
      {trStrictPrivate} 'Estrictamente privado', //'Strict Private',
      {trProtected} 'Protegido', //?
      {trStrictProtected} 'Estrictamente protegido', //'Strict Protected',
      {trPublic} 'Público', //'Public',
      {trPublished} strToDo, //'Published', I would keep that because "Published" is also "Público" in this context (IDE).
      {trAutomated} 'Automático', //'Automated',
      {trImplicit} 'Implícito', //'Implicit',
  //hints
    {trDeprecated} 'Este símbolo es obsoleto', //
    {trPlatformSpecific} 'Este símbolo es específico para alguna plataforma',
    {trLibrarySpecific} 'Este símbolo es específico para alguna biblioteca', //
    {trExperimental} strToDo, //'this symbol is experimental',
  //headings
    {trOverview} 'Resumen',
    {trIntroduction} 'Introducción',
    {trConclusion} 'Conclusión',
    {trAdditionalFile} strToDo, //'additional file',
    {trEnclosingClass} strToDo, //'Enclosing Class',
    {trHeadlineCio} 'Todas las clases, interfaces y objetos',
    {trHeadlineConstants} 'Todas las constantes',
    {trHeadlineFunctionsAndProcedures} 'Todos las funciones y procedimientos',
    {trHeadlineIdentifiers} 'Todos los indentificadores',
    {trHeadlineTypes} 'Todos los tipos',
    {trHeadlineUnits} 'Todas las unidades',
    {trHeadlineVariables} 'Todas las variables',
    {trSummaryCio} 'Lista de clases, interfaces y objetos',
  //column headings
    {trDeclaration} 'Declaración',
    {trDescription} 'Descripción',
    {trDescriptions} 'Descripción detallada', //? 'Descriptions', 'Detailed Descriptions'?
    {trName} 'Nombre',
    {trValues} 'Valores',
  //empty
    {trNone} 'Ninguno',
    {trNoCIOs} 'Las unidades no contienen clases, interfaces, objetos ni registros.',
    {trNoCIOsForHierarchy} 'Las unidades no contienen clases, interfaces ni objetos.',
    {trNoTypes} 'Las unidades no contienen tipo alguno.',
    {trNoVariables} 'Las unidades no contienen ninguna variable.', //
    {trNoConstants} 'Las unidades no contienen ninguna constante.', //
    {trNoFunctions} 'Las unidades no contienen funciones ni procedimientos', //
    {trNoIdentifiers} 'Las unidades no contienen identificadores.',
  //misc
    {trHelp} 'Ayuda',
    {trLegend} 'Leyenda',
    {trMarker} 'Marcador',
    {trWarningOverwrite} 'Atención, no editar - este fichero ha sido creado automaticamente y puede ser sobrescrito',
    {trWarning} 'Atención',
    {trGeneratedBy} 'Generado por', //??? strToDo, //'Generador por',
    {trGeneratedOn} strToDo, //'Generated on'
    {trOnDateTime} 'a',
    {trSearch} 'Buscar',
    {trSeeAlso} 'Ver también', // ?
    {trNested} strToDo, //'nested',
    {trAttributes} 'Atributos', //'Attributes',
    ''  //dummy
  );
