RTransTable = (
    {trNoTrans} '<what?>', //no ID assigned, so far
    {trLanguage} 'French',
  //map
    {trUnits} 'Unités',
    {trClassHierarchy} 'Hiérarchie des classes',
    {trCio} 'Classes, interfaces, structures et objets',
    {trInternalCR} strToDo, // 'Internal Classes and Records',
    {trInternalTypes} strToDo, // 'Internal Types',
    {trIdentifiers} 'Identificateurs',
    {trGvUses} 'Graphique de dépendance d''unités',
    {trGvClasses} 'Graphique de hiérarchie des classes',
  //tables and members
    {trClasses} strKeep, //'Classes',
      {trClass} 'Classe',
      {trDispInterface} strToDo, //'DispInterface',
      {trInterface} strToDo, //'Interface',
    {trObjects} 'Objets',
      {trObject} 'Objet',
      {trRecord} strToDo, //'Record',
        {trHierarchy} 'Hiérarchie',
        {trFields} 'Champs',
        {trMethods} 'Méthodes',
        {trProperties} 'Propriétés',
    {trLibrary} 'Bibliothèque', //?
    {trPackage} strToDo,  //'Package',
    {trProgram} 'Logiciel', //? 'Program',
    {trUnit} 'Unité',
      {trUses} strToDo, //'Uses',
      {trConstants} 'Constantes',
      {trFunctionsAndProcedures} 'Fonctions et procédures',
      {trTypes} strKeep, //'Types',
        {trType} strKeep, //'Type',
      {trVariables} strKeep, //'Variables',
      {trAuthors} 'Auteurs',
        {trAuthor} 'Auteur',
      {trCreated} 'Crée',
      {trLastModified} 'Dernière modification',
    {trSubroutine} strToDo, //'Subroutine',
      {trParameters} 'Paramètres',
      {trReturns} 'Retourne',
      {trExceptionsRaised} strToDo, //'Exceptions raised',
    {trExceptions} strToDo, //'Exceptions',
      {trException} strToDo, //'Exception',
    {trEnum} strToDo, //'Enumeration',
  //visibilities
    {trVisibility} 'Visibilité',
      {trPrivate} 'Privé',
      {trStrictPrivate} 'Strictement Privé', //?
      {trProtected} 'Protégé',
      {trStrictProtected} 'Strictement Protégé', //?
      {trPublic} strKeep, //'Public',
      {trPublished} 'Publiés',
      {trAutomated} 'Automatisé',
      {trImplicit} strKeep, //'Implicit',
  //hints
    {trDeprecated} 'ce symbole est désapprouvé',
    {trPlatformSpecific} 'ce symbole est spécifique à une plateforme d''exécution',
    {trLibrarySpecific} 'ce symbole est spécifique à une certaine bibliothèque',
  //headings
    {trOverview} 'Aperçu',
    {trIntroduction} strToDo, //'Introduction',
    {trConclusion} strToDo, //'Conclusion',
    {trHeadlineCio} 'Toutes les classes, interfaces, objets et enregistrements',
    {trHeadlineConstants} 'Toutes les constants',
    {trHeadlineFunctionsAndProcedures} 'Toutes les fonctions et procédures',
    {trHeadlineIdentifiers} 'Tous les identificateurs',
    {trHeadlineTypes} 'Tous les types',
    {trHeadlineUnits} 'Toutes les unités',
    {trHeadlineVariables} 'Toutes les variables',
    {trSummaryCio} 'Classes, interfaces, objets et enregistrements',
  //column headings
    {trDeclaration} 'Déclaration',
    {trDescription} strKeep, //'Description',
    {trDescriptions} strToDo, //'Descriptions', 'Detailed Descriptions'?
    {trName} 'Nom',
    {trValues} 'Valeurs', //?
  //empty
    {trNone} 'Aucun(e)(s)', //'Rien'?
    {trNoCIOs} strToDo, //'The units do not contain any classes, interfaces, objects or records.',
    {trNoCIOsForHierarchy} strToDo, //'The units do not contain any classes, interfaces or objects.',
    {trNoTypes} strToDo, //'The units do not contain any types.',
    {trNoVariables} strToDo, //'The units do not contain any variables.',
    {trNoConstants} strToDo, //'The units do not contain any constants.',
    {trNoFunctions} strToDo, //'The units do not contain any functions or procedures.',
    {trNoIdentifiers} strToDo, //'The units do not contain any identifiers.',
  //misc
    {trHelp} 'Aide',
    {trLegend} 'Légende',
    {trMarker} 'Marquage',
    {trWarningOverwrite} 'Attention, ne pas édtier - ce fichier est créé automatiquement et va être écrasé',
    {trWarning} 'Attention',
    {trGeneratedBy} 'Produit par',
    {trGeneratedOn} strToDo, //'Generated on'
    {trOnDateTime} 'le',
    {trSearch} 'Cherche', //? 'Recherche'
    {trSeeAlso} 'Voir aussi', //?
    {trInternal} strToDo, //'internal',
    {trAttributes} strToDo, //'Attributes',
    ''  //dummy
  );
  