<?php
global $pasdoc;
$pasdoc = array(
  'ok_vorbisfile' => array('html_filename' => 'ok_vorbisfile.html', 'type' => 'unit'),
  'NOTOPEN' => array('html_filename' => 'ok_vorbisfile.html#NOTOPEN', 'type' => 'constant'),
  'PARTOPEN' => array('html_filename' => 'ok_vorbisfile.html#PARTOPEN', 'type' => 'constant'),
  'OPENED' => array('html_filename' => 'ok_vorbisfile.html#OPENED', 'type' => 'constant'),
  'STREAMSET' => array('html_filename' => 'ok_vorbisfile.html#STREAMSET', 'type' => 'constant'),
  'INITSET' => array('html_filename' => 'ok_vorbisfile.html#INITSET', 'type' => 'constant'),
  'ov_clear' => array('html_filename' => 'ok_vorbisfile.html#ov_clear', 'type' => 'variable'),
  'VorbisFileInited' => array('html_filename' => 'ok_vorbisfile.html#VorbisFileInited', 'type' => 'variable'),
  'TSizeT' => array('html_filename' => 'ok_vorbisfile.html#TSizeT', 'type' => 'type'),
  'TVorbisFileReadFunc' => array('html_filename' => 'ok_vorbisfile.html#TVorbisFileReadFunc', 'type' => 'type'),
  'TVorbisFileSeekFunc' => array('html_filename' => 'ok_vorbisfile.html#TVorbisFileSeekFunc', 'type' => 'type'),
  'TVorbisFileCloseFunc' => array('html_filename' => 'ok_vorbisfile.html#TVorbisFileCloseFunc', 'type' => 'type'),
  'TVorbisFileTellFunc' => array('html_filename' => 'ok_vorbisfile.html#TVorbisFileTellFunc', 'type' => 'type'),
  'Pov_callbacks' => array('html_filename' => 'ok_vorbisfile.html#Pov_callbacks', 'type' => 'type'),
  'POggVorbis_File' => array('html_filename' => 'ok_vorbisfile.html#POggVorbis_File', 'type' => 'type'),
  'Tov_callbacks' => array('html_filename' => 'ok_vorbisfile.Tov_callbacks.html', 'type' => 'record'),
  'Tov_callbacks.read_func' => array('html_filename' => 'ok_vorbisfile.Tov_callbacks.html#read_func', 'type' => 'variable'),
  'Tov_callbacks.seek_func' => array('html_filename' => 'ok_vorbisfile.Tov_callbacks.html#seek_func', 'type' => 'variable'),
  'Tov_callbacks.close_func' => array('html_filename' => 'ok_vorbisfile.Tov_callbacks.html#close_func', 'type' => 'variable'),
  'Tov_callbacks.tell_func' => array('html_filename' => 'ok_vorbisfile.Tov_callbacks.html#tell_func', 'type' => 'variable'),
  'TOggVorbis_File' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html', 'type' => 'record'),
  'TOggVorbis_File.datasource' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#datasource', 'type' => 'variable'),
  'TOggVorbis_File.seekable' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#seekable', 'type' => 'variable'),
  'TOggVorbis_File.offset' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#offset', 'type' => 'variable'),
  'TOggVorbis_File._end' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#_end', 'type' => 'variable'),
  'TOggVorbis_File.oy' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#oy', 'type' => 'variable'),
  'TOggVorbis_File.links' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#links', 'type' => 'variable'),
  'TOggVorbis_File.offsets' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#offsets', 'type' => 'variable'),
  'TOggVorbis_File.dataoffsets' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#dataoffsets', 'type' => 'variable'),
  'TOggVorbis_File.serialnos' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#serialnos', 'type' => 'variable'),
  'TOggVorbis_File.pcmlengths' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#pcmlengths', 'type' => 'variable'),
  'TOggVorbis_File.vi' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#vi', 'type' => 'variable'),
  'TOggVorbis_File.vc' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#vc', 'type' => 'variable'),
  'TOggVorbis_File.pcm_offset' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#pcm_offset', 'type' => 'variable'),
  'TOggVorbis_File.ready_state' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#ready_state', 'type' => 'variable'),
  'TOggVorbis_File.current_serialno' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#current_serialno', 'type' => 'variable'),
  'TOggVorbis_File.current_link' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#current_link', 'type' => 'variable'),
  'TOggVorbis_File.bittrack' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#bittrack', 'type' => 'variable'),
  'TOggVorbis_File.samptrack' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#samptrack', 'type' => 'variable'),
  'TOggVorbis_File.os' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#os', 'type' => 'variable'),
  'TOggVorbis_File.vd' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#vd', 'type' => 'variable'),
  'TOggVorbis_File.vb' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#vb', 'type' => 'variable'),
  'TOggVorbis_File.callbacks' => array('html_filename' => 'ok_vorbisfile.TOggVorbis_File.html#callbacks', 'type' => 'variable'),
);
