<?php
global $pasdoc;
$pasdoc = array(
  'ok_type_aliases' => array('html_filename' => 'ok_type_aliases.html', 'type' => 'unit'),
  'Test' => array('html_filename' => 'ok_type_aliases.html#Test', 'type' => 'procedure'),
  'TWeakAliasType' => array('html_filename' => 'ok_type_aliases.html#TWeakAliasType', 'type' => 'type'),
  'TStrongAliasType' => array('html_filename' => 'ok_type_aliases.html#TStrongAliasType', 'type' => 'type'),
  'TWeakAliasType2' => array('html_filename' => 'ok_type_aliases.html#TWeakAliasType2', 'type' => 'type'),
  'TStrongAliasType2' => array('html_filename' => 'ok_type_aliases.html#TStrongAliasType2', 'type' => 'type'),
  'TWeakAliasType3' => array('html_filename' => 'ok_type_aliases.html#TWeakAliasType3', 'type' => 'type'),
  'TStrongAliasType3' => array('html_filename' => 'ok_type_aliases.html#TStrongAliasType3', 'type' => 'type'),
  'TWeakAliasTypeVeryNested' => array('html_filename' => 'ok_type_aliases.html#TWeakAliasTypeVeryNested', 'type' => 'type'),
  'TStrongAliasTypeVeryNested' => array('html_filename' => 'ok_type_aliases.html#TStrongAliasTypeVeryNested', 'type' => 'type'),
  'TOriginalType' => array('html_filename' => 'ok_type_aliases.TOriginalType.html', 'type' => 'record'),
  'TOriginalType.x' => array('html_filename' => 'ok_type_aliases.TOriginalType.html#x', 'type' => 'variable'),
  'TOriginalType.y' => array('html_filename' => 'ok_type_aliases.TOriginalType.html#y', 'type' => 'variable'),
  'TOriginalType2' => array('html_filename' => 'ok_type_aliases.TOriginalType2.html', 'type' => 'record'),
  'TOriginalType2.x' => array('html_filename' => 'ok_type_aliases.TOriginalType2.html#x', 'type' => 'variable'),
  'TOriginalType2.y' => array('html_filename' => 'ok_type_aliases.TOriginalType2.html#y', 'type' => 'variable'),
  'TOriginalType3' => array('html_filename' => 'ok_type_aliases.TOriginalType3.html', 'type' => 'record'),
  'TOriginalType3.x' => array('html_filename' => 'ok_type_aliases.TOriginalType3.html#x', 'type' => 'variable'),
  'TOriginalType3.y' => array('html_filename' => 'ok_type_aliases.TOriginalType3.html#y', 'type' => 'variable'),
  'TMyClass' => array('html_filename' => 'ok_type_aliases.TMyClass.html', 'type' => 'class'),
  'TMyClass.TMyNestedClass' => array('html_filename' => 'ok_type_aliases.TMyClass.TMyNestedClass.html', 'type' => 'class'),
  'TMyClass.TMyNestedClass.TAnotherNestedClass' => array('html_filename' => 'ok_type_aliases.TMyClass.TMyNestedClass.TAnotherNestedClass.html', 'type' => 'class'),
  'TMyClass.TMyNestedClass.TAnotherNestedClass.TOriginalType' => array('html_filename' => 'ok_type_aliases.TMyClass.TMyNestedClass.TAnotherNestedClass.TOriginalType.html', 'type' => 'record'),
  'TMyClass.TMyNestedClass.TAnotherNestedClass.TOriginalType.x' => array('html_filename' => 'ok_type_aliases.TMyClass.TMyNestedClass.TAnotherNestedClass.TOriginalType.html#x', 'type' => 'variable'),
  'TMyClass.TMyNestedClass.TAnotherNestedClass.TOriginalType.y' => array('html_filename' => 'ok_type_aliases.TMyClass.TMyNestedClass.TAnotherNestedClass.TOriginalType.html#y', 'type' => 'variable'),
);
