<?php
global $pasdoc;
$pasdoc = array(
  'ok_generic' => array('html_filename' => 'ok_generic.html', 'type' => 'unit'),
  'TGeometryAttribsList2' => array('html_filename' => 'ok_generic.html#TGeometryAttribsList2', 'type' => 'type'),
  'TMyList' => array('html_filename' => 'ok_generic.TMyList.html', 'type' => 'class'),
  'TMyList.Blah' => array('html_filename' => 'ok_generic.TMyList.html#Blah', 'type' => 'function'),
  'TGeometryAttrib' => array('html_filename' => 'ok_generic.TGeometryAttrib.html', 'type' => 'class'),
  'TGeometryAttrib.Name' => array('html_filename' => 'ok_generic.TGeometryAttrib.html#Name', 'type' => 'variable'),
  'TGeometryAttrib.AType' => array('html_filename' => 'ok_generic.TGeometryAttrib.html#AType', 'type' => 'variable'),
  'TGeometryAttrib.Offset' => array('html_filename' => 'ok_generic.TGeometryAttrib.html#Offset', 'type' => 'variable'),
  'TGeometryAttribsList' => array('html_filename' => 'ok_generic.TGeometryAttribsList.html', 'type' => 'class'),
  'TGeometryAttribsList.Find' => array('html_filename' => 'ok_generic.TGeometryAttribsList.html#Find', 'type' => 'function'),
  'TMyObject' => array('html_filename' => 'ok_generic.TMyObject.html', 'type' => 'class'),
  'TMyGenericList' => array('html_filename' => 'ok_generic.TMyGenericList.html', 'type' => 'class'),
  'TMyNewGeneric' => array('html_filename' => 'ok_generic.TMyNewGeneric.html', 'type' => 'class'),
  'TMyNewGeneric.Blah' => array('html_filename' => 'ok_generic.TMyNewGeneric.html#Blah', 'type' => 'function'),
  'TAnotherGenericType' => array('html_filename' => 'ok_generic.TAnotherGenericType.html', 'type' => 'class'),
  'TArray' => array('html_filename' => 'ok_generic.TArray.html', 'type' => 'class'),
  'TEnumerator' => array('html_filename' => 'ok_generic.TEnumerator.html', 'type' => 'class'),
  'TEnumerable' => array('html_filename' => 'ok_generic.TEnumerable.html', 'type' => 'class'),
  'TList' => array('html_filename' => 'ok_generic.TList.html', 'type' => 'class'),
  'TQueue' => array('html_filename' => 'ok_generic.TQueue.html', 'type' => 'class'),
  'TStack' => array('html_filename' => 'ok_generic.TStack.html', 'type' => 'class'),
  'TPair' => array('html_filename' => 'ok_generic.TPair.html', 'type' => 'record'),
  'TDictionary' => array('html_filename' => 'ok_generic.TDictionary.html', 'type' => 'class'),
  'TObjectList' => array('html_filename' => 'ok_generic.TObjectList.html', 'type' => 'class'),
  'TObjectQueue' => array('html_filename' => 'ok_generic.TObjectQueue.html', 'type' => 'class'),
  'TObjectStack' => array('html_filename' => 'ok_generic.TObjectStack.html', 'type' => 'class'),
  'TObjectDictionary' => array('html_filename' => 'ok_generic.TObjectDictionary.html', 'type' => 'class'),
);
