{ Simplified Chinese (Codepage 936, GB2312) Translation updated by Liu Da <xmacmail AT gmail.com>
  Based on translation made by Liu Chuanjun <1000copy AT gmail.com> ( Thank you )
  Thanks to the authors and all contributors of Pasdoc. :-D
}

procedure TPasDocLanguages.SetLanguageChinese_gb2312;
begin
  FTranslation[trAuthor] := '作者';
  FTranslation[trAuthors] := '作者';
  FTranslation[trAutomated] := 'Automated';
  FTranslation[trCio] := '类、接口、对象和记录';
  FTranslation[trClass] := '类';
  FTranslation[trClasses] := '类';
  FTranslation[trClassHierarchy] := '类继承';
  FTranslation[trConstants] := '常量';
  FTranslation[trCreated] := '创建时间';
  FTranslation[trDeclaration] := '声明';
  FTranslation[trDescription] := '描述';
  FTranslation[trParameters] := '参数列表';
  FTranslation[trReturns] := '返回值';
  FTranslation[trExceptions] := '异常';
  FTranslation[trExceptionsRaised] := '抛出的异常';
  FTranslation[trEnum] := '枚举';
  FTranslation[trDispInterface] := 'DispInterface';
  FTranslation[trFields] := '字段';
  FTranslation[trFunctionsAndProcedures] := '函数与过程';
  FTranslation[trHelp] := '帮助';
  FTranslation[trHierarchy] := '继承';
  FTranslation[trIdentifiers] := '标识符';
  FTranslation[trInterface] := '接口';
  FTranslation[trLegend] := '图例';
  FTranslation[trMarker] := '标记';
  FTranslation[trVisibility] := '可见性';
  FTranslation[trMethods] := '方法';
  FTranslation[trLastModified] := '最近修改';
  FTranslation[trName] := '名字';
  FTranslation[trNone] := '无';
  FTranslation[trObject] := '对象';
  FTranslation[trObjects] := '对象';
  FTranslation[trOverview] := '概要';
  FTranslation[trPrivate] := '私有';
  FTranslation[trStrictPrivate] := '严格私有';
  FTranslation[trProperties] := '属性';
  FTranslation[trProtected] := '保护';
  FTranslation[trStrictProtected] := '严格保护';
  FTranslation[trPublic] := '公共';
  FTranslation[trImplicit] := '内含';
  FTranslation[trPublished] := '发布';
  FTranslation[trType] := '数据类型';
  FTranslation[trTypes] := '数据类型';
  FTranslation[trUnit] := '单元';
  FTranslation[trUnits] := '单元';
  FTranslation[trVariables] := '变量';
  FTranslation[trGvUses] := '单元依赖图';
  FTranslation[trGvClasses] := '类继承图';
  FTranslation[trHeadlineCio] := '全部类、接口、对象和记录';
  FTranslation[trHeadlineConstants] := '全部常量';
  FTranslation[trHeadlineFunctionsAndProcedures] := '全部函数';
  FTranslation[trHeadlineIdentifiers] := '全部标识符';
  FTranslation[trHeadlineTypes] := '全部数据类型';
  FTranslation[trHeadlineUnits] := '全部单元';
  FTranslation[trHeadlineVariables] := '全部变量';
  FTranslation[trSummaryCio] := '类、接口、对象和记录的摘要';
  FTranslation[trWarningOverwrite] :=
    '警告：不要编辑本文件 - 这是一个自动生成的文件，而且它很可能被覆盖掉。';
  FTranslation[trWarning] := '警告';
  FTranslation[trGeneratedBy] := '由';
  FTranslation[trOnDateTime] := '生成于';
  FTranslation[trDeprecated] := '这个符号已经过期';
  FTranslation[trPlatformSpecific] := '这个符号仅仅用于特定平台';
  FTranslation[trLibrarySpecific] := '这个符号仅仅用于特定的库';
  FTranslation[trIntroduction] := '前言';
  FTranslation[trConclusion] := '后记';
  FTranslation[trSearch] := '搜索';
  FTranslation[trSeeAlso] := '参见';
  FTranslation[trValues] := '值';
  FTranslation[trNoCIOs] := '本单元没有包括任何类、接口、对象和记录';
  FTranslation[trNoCIOsForHierarchy] := '本单元没有包括任何类、接口和对象';
  FTranslation[trNoTypes] := '本单元没有包括任何数据类型';
  FTranslation[trNoVariables] := '本单元没有任何变量';
  FTranslation[trNoConstants] := '本单元没有任何常量';
  FTranslation[trNoFunctions] := '本单元没有任何函数和过程';
  FTranslation[trNoIdentifiers] := '本单元没有任何标识符';
  FTranslation[trProgram] := '程序';
  FTranslation[trLibrary] := '库';
end;


 	  	 
