#!/bin/bash
set -eu

# This scripts runs onsgmls to check every *.html file in current directory.
# It's meant to be run using `make validate_html' in parent directory.
# But let's also try to keep this script in a state of a generally-useful
# script to allow pasdoc users to easily check their
# own html documentation generated by pasdoc using this script.
#
# See ../README for comments.

for FFF in *.html; do
  if [ "$FFF" = index.html ]; then
    echo "---- Not validating $FFF due to problems with Cygwin's onsgmls"
  else
    echo "---- Validating $FFF"
    onsgmls -s -e -g "$FFF"
  fi
done